### ISSUE TITLE
Traceback - weedmaps.settings

### ISSUE THREAD

**Issue by mehh** [gangabass/weedmaps#1]
Upon cloning project, and attempting to run from top level parent directory, I receive the following:

`Traceback (most recent call last):
  File "/usr/local/bin/scrapy", line 11, in <module>
    sys.exit(execute())
  File "/usr/local/lib/python2.7/site-packages/scrapy/cmdline.py", line 108, in execute
    settings = get_project_settings()
  File "/usr/local/lib/python2.7/site-packages/scrapy/utils/project.py", line 68, in get_project_settings
    settings.setmodule(settings_module_path, priority='project')
  File "/usr/local/lib/python2.7/site-packages/scrapy/settings/__init__.py", line 292, in setmodule
    module = import_module(module)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named weedmaps.settings`

**Comment by gangabass** [comment]
Fixed! Please try it again.

It was empty __init__.py file (github web interface didn't upload it for some reason).

Also `output` folder added

Thanks.
Roman

**Comment by mehh** [comment]
I should have provided an update, I was able to figure that out too :)

Thanks for the follow up!
